name: Баг-репорт
description: Если что-то работает не так
labels: [status:triage, type:bug]
body:
  
  - type: markdown
    attributes:
      value: |
        - Баг-репорты нужны для сообщения о неправильно работающих функциях, предложения находятся в другом разделе
        - Попробуй [поискать в существующих репортах](https://github.com/octothorp-team/public-dobrograd/issues?q=is%3Aopen+is%3Aissue+label%3Abug), может быть, кто-то уже рассказал об этой ошибке
        - Каждая ошибка должна быть в отдельном репорте, не стоит создавать списки

  - type: textarea
    id: what-happened
    attributes:
      label: Что наблюдается?
      description: Опиши подробно, что именно происходит на момент написания репорта
      placeholder: Кнопка не нажимается, ничего не происходит...
    validations:
      required: true

  - type: textarea
    id: correct-behaviour
    attributes:
      label: Как это должно работать?
      description: Как, по твоему мнению, это должно работать, что нужно изменить
      placeholder: После нажатия кнопки должно открываться меню!
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Как это повторить?
      description: Пошагово опиши, как повторить эту ошибку
      placeholder: 1) Открыть меню на клавишу X. 2) Нажать на кнопку ABC. 3) ???
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Обратная связь
      description: Если нам понадобится что-то уточнить, как с тобой связаться?
      placeholder: "например, Discord: username#1234"
    validations:
      required: false
